### ISSUE TITLE
Issue with flutter_svg

### ISSUE THREAD

**Issue by ZaifSenpai** [ZaifSenpai/dice_bear#1]
There is an issue with [flutter_svg](https://pub.dev/packages/flutter_svg) package which is not rendering some svg images. I have mentioned this issue [here](https://github.com/dnfield/flutter_svg/issues/641#issue-1093605146).

I am thinking to use a different approach. That is, converting the SVG to PNG using [cloudconvert API](https://cloudconvert.com/api/v2/quickstart#quickstart-start)

**Comment by FlorianKoerner** [comment]
I will take a look at the problem. But you don't need Cloudconvert as a workaround.

https://github.com/dicebear/dicebear/discussions/179

**Comment by FlorianKoerner** [comment]
The problem should not exist with the 5.0 alpha. Here is an example URL:

https://api.dicebear.com/5.x/adventurer/svg?size=150&seed=dhhfjjs

**Comment by ZaifSenpai** [comment]
> The problem should not exist with the 5.0 alpha. Here is an example URL:
> 
> https://api.dicebear.com/5.x/adventurer/svg?size=150&seed=dhhfjjs

Thank you very much. The issue is solved by using 5.x
